name: Cards Guard CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'September2025/TectangleHexagonal/dev/gesture_shell_os_v1.html'
      - 'September2025/TectangleHexagonal/src/ui/components/**'
      - 'September2025/TectangleHexagonal/src/ui/cards/**'
      - 'September2025/TectangleHexagonal/tests/e2e/cards_registry_validation.test.js'
      - 'package.json'
      - 'jest-puppeteer.config.cjs'

jobs:
  cards-guard:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Start static server (8080)
        run: npx http-server . -p 8080 &

      - name: Wait for server
        run: |
          powershell -NoProfile -Command "for ($i=0; $i -lt 20; $i++) { try { (Invoke-WebRequest -UseBasicParsing http://127.0.0.1:8080) | Out-Null; exit 0 } catch { Start-Sleep -Seconds 1 } }; exit 1"

      - name: Run cards registry guard
        env:
          JEST_PUPPETEER_CONFIG: jest-puppeteer.config.cjs
          SITE_BASE: http://127.0.0.1:8080
          VIEWPORT: 1280x720
        run: npm run -s hex:cards:guard
