# Stubbed to keep repository history while inactive.
name: Legacy Stub - HFO Prepare

on:
  workflow_dispatch:

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - name: Stub notice
        run: |
          echo "HiveFleetObsidian automation disabled while focusing on Tectangle Hexagonal."
          echo "Restore the original workflow when this flow is needed again."
