# Stubbed to keep repository history while inactive.
name: Legacy Stub - PinchFSM Goldens

on:
  workflow_dispatch:

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - name: Stub notice
        run: |
          echo "PinchFSM golden generation disabled while inactive."
          echo "Restore the original workflow when this flow is needed again."
